// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 3.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){this.go=function(d){b.find("ul").stop(true).animate({left:(d?-d+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},c.duration,"easeInOutExpo");return d}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 3.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:20*100,delay:20*100,width:900,height:425,autoPlay:true,stopOnHover:true,loop:false,bullets:0,caption:true,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./ourteam.jpg",title:"Newsletter Sign-Up"},{src:"./intensive_care_unit.jpg",title:"News & Blog"},{src:"./stateoftheartinfrastructure.jpg",title:"Events"},{src:"./orthodentalservices.jpg",title:"Donate Today"},{src:"./gynaecology.jpg",title:"Volunteer Opportunities"}]});